//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDKMenShop.Resrources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KDKMenShop.Resrources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áo sơ mi.
        /// </summary>
        public static string Áo_sơ_mi {
            get {
                return ResourceManager.GetString("Áo sơ mi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áo thun.
        /// </summary>
        public static string Áo_thun {
            get {
                return ResourceManager.GetString("Áo thun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balo.
        /// </summary>
        public static string Balo {
            get {
                return ResourceManager.GetString("Balo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần tìm?.
        /// </summary>
        public static string Bạn_cần_tìm_ {
            get {
                return ResourceManager.GetString("Bạn cần tìm?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ Sưu Tập.
        /// </summary>
        public static string Bộ_Sưu_Tập {
            get {
                return ResourceManager.GetString("Bộ Sưu Tập", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ngôn ngữ.
        /// </summary>
        public static string Chọn_ngôn_ngữ {
            get {
                return ResourceManager.GetString("Chọn ngôn ngữ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách sản phẩm.
        /// </summary>
        public static string Danh_sách_sản_phẩm {
            get {
                return ResourceManager.GetString("Danh sách sản phẩm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giày.
        /// </summary>
        public static string Giày {
            get {
                return ResourceManager.GetString("Giày", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ 24/7.
        /// </summary>
        public static string Hỗ_trợ_24_7 {
            get {
                return ResourceManager.GetString("Hỗ trợ 24/7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên Hệ.
        /// </summary>
        public static string Liên_Hệ {
            get {
                return ResourceManager.GetString("Liên Hệ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quần Jean.
        /// </summary>
        public static string Quần_Jean {
            get {
                return ResourceManager.GetString("Quần Jean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Giá Hời.
        /// </summary>
        public static string Sale_Giá_Hời {
            get {
                return ResourceManager.GetString("Sale Giá Hời", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Tìm_kiếm {
            get {
                return ResourceManager.GetString("Tìm kiếm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang Chủ.
        /// </summary>
        public static string Trang_Chủ {
            get {
                return ResourceManager.GetString("Trang Chủ", resourceCulture);
            }
        }
    }
}
